* Additional include directories for windres (configure-based build in MSW) taken from wx-config -> NEEDS TESTING
svn path=/trunk/flamerobin/; revision=1244

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="aclocal.m4"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT WX_CONFIG_PATH WX_CPPFLAGS WX_CFLAGS WX_CXXFLAGS WX_CFLAGS_ONLY WX_CXXFLAGS_ONLY WX_LIBS WX_LIBS_STATIC WX_VERSION RANLIB ac_ct_RANLIB INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S SET_MAKE MAKE_SET AR ac_ct_AR STRIP ac_ct_STRIP NM ac_ct_NM INSTALL_DIR LDFLAGS_GUI IF_GNU_MAKE PLATFORM_UNIX PLATFORM_WIN32 PLATFORM_MSDOS PLATFORM_MAC PLATFORM_MACOS PLATFORM_MACOSX PLATFORM_OS2 PLATFORM_BEOS SO_SUFFIX SO_SUFFIX_MODULE DLLIMP_SUFFIX LIBPREFIX LIBEXT DLLPREFIX DLLPREFIX_MODULE dlldir CC CFLAGS ac_ct_CC AIX_CXX_LD SHARED_LD_CC SHARED_LD_CXX SHARED_LD_MODULE_CC SHARED_LD_MODULE_CXX PIC_FLAG WINDOWS_IMPLIB USE_SOVERSION USE_SOVERLINUX USE_SOVERSOLARIS USE_SOVERCYGWIN USE_MACVERSION USE_SOSYMLINKS SONAME_FLAG DEPS_TRACKING RESCOMP SETFILE GCC_PCH COND_DEPS_TRACKING_0 COND_DEPS_TRACKING_1 COND_FINAL_0 COND_FINAL_1 COND_GCC_PCH_1 COND_PLATFORM_MACOSX_1 COND_PLATFORM_MAC_1 COND_PLATFORM_OS2_1 COND_PLATFORM_UNIX_1 COND_PLATFORM_WIN32_1 COND_STATICRTL_0 COND_STATICRTL_1 COND_UNICODE_1 COND_USEDLL_1 LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT WX_CONFIG_PATH WX_CPPFLAGS WX_CFLAGS WX_CXXFLAGS WX_CFLAGS_ONLY WX_CXXFLAGS_ONLY WX_LIBS WX_LIBS_STATIC WX_VERSION RANLIB ac_ct_RANLIB INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S SET_MAKE MAKE_SET AR ac_ct_AR STRIP ac_ct_STRIP NM ac_ct_NM INSTALL_DIR LDFLAGS_GUI IF_GNU_MAKE PLATFORM_UNIX PLATFORM_WIN32 PLATFORM_MSDOS PLATFORM_MAC PLATFORM_MACOS PLATFORM_MACOSX PLATFORM_OS2 PLATFORM_BEOS SO_SUFFIX SO_SUFFIX_MODULE DLLIMP_SUFFIX LIBPREFIX LIBEXT DLLPREFIX DLLPREFIX_MODULE dlldir CC CFLAGS ac_ct_CC AIX_CXX_LD SHARED_LD_CC SHARED_LD_CXX SHARED_LD_MODULE_CC SHARED_LD_MODULE_CXX PIC_FLAG WINDOWS_IMPLIB USE_SOVERSION USE_SOVERLINUX USE_SOVERSOLARIS USE_SOVERCYGWIN USE_MACVERSION USE_SOSYMLINKS SONAME_FLAG DEPS_TRACKING RESCOMP SETFILE GCC_PCH COND_DEPS_TRACKING_0 COND_DEPS_TRACKING_1 COND_FINAL_0 COND_FINAL_1 COND_GCC_PCH_1 COND_ICC_PCH_1 COND_PLATFORM_MACOSX_1 COND_PLATFORM_MAC_1 COND_PLATFORM_OS2_1 COND_PLATFORM_UNIX_1 COND_PLATFORM_WIN32_1 COND_STATICRTL_0 COND_STATICRTL_1 COND_UNICODE_1 COND_USEDLL_1 COND_USE_PCH_1 WX_INCLUDES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -820,11 +820,11 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-wxdir=PATH       Use uninstalled version of wxWindows in PATH
+  --with-wxdir=PATH       Use uninstalled version of wxWidgets in PATH
   --with-wx-config=CONFIG wx-config script to use (optional)
-  --with-wx-prefix=PREFIX Prefix where wxWindows is installed (optional)
+  --with-wx-prefix=PREFIX Prefix where wxWidgets is installed (optional)
   --with-wx-exec-prefix=PREFIX
-                          Exec prefix where wxWindows is installed (optional)
+                          Exec prefix where wxWidgets is installed (optional)
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -2064,11 +2064,11 @@ fi
 
     min_wx_version=2.6.0
     if test -z "" ; then
-      echo "$as_me:$LINENO: checking for wxWindows version >= $min_wx_version" >&5
-echo $ECHO_N "checking for wxWindows version >= $min_wx_version... $ECHO_C" >&6
+      echo "$as_me:$LINENO: checking for wxWidgets version >= $min_wx_version" >&5
+echo $ECHO_N "checking for wxWidgets version >= $min_wx_version... $ECHO_C" >&6
     else
-      echo "$as_me:$LINENO: checking for wxWindows version >= $min_wx_version ()" >&5
-echo $ECHO_N "checking for wxWindows version >= $min_wx_version ()... $ECHO_C" >&6
+      echo "$as_me:$LINENO: checking for wxWidgets version >= $min_wx_version ()" >&5
+echo $ECHO_N "checking for wxWidgets version >= $min_wx_version ()... $ECHO_C" >&6
     fi
 
     WX_CONFIG_WITH_ARGS="$WX_CONFIG_PATH $wx_config_args  stc,std"
@@ -2087,6 +2087,7 @@ echo $ECHO_N "checking for wxWindows version >= $min_wx_version ()... $ECHO_C" >
            sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\2/'`
     wx_requested_micro_version=`echo $min_wx_version | \
            sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\3/'`
+
 
     wx_ver_ok=""
     if test "x$WX_VERSION" != x ; then
@@ -2107,14 +2108,15 @@ echo $ECHO_N "checking for wxWindows version >= $min_wx_version ()... $ECHO_C" >
       fi
     fi
 
+
     if test -n "$wx_ver_ok"; then
 
       echo "$as_me:$LINENO: result: yes (version $WX_VERSION)" >&5
 echo "${ECHO_T}yes (version $WX_VERSION)" >&6
       WX_LIBS=`$WX_CONFIG_WITH_ARGS --libs`
 
-                              echo "$as_me:$LINENO: checking for wxWindows static library" >&5
-echo $ECHO_N "checking for wxWindows static library... $ECHO_C" >&6
+                              echo "$as_me:$LINENO: checking for wxWidgets static library" >&5
+echo $ECHO_N "checking for wxWidgets static library... $ECHO_C" >&6
       WX_LIBS_STATIC=`$WX_CONFIG_WITH_ARGS --static --libs 2>/dev/null`
       if test "x$WX_LIBS_STATIC" = "x"; then
         echo "$as_me:$LINENO: result: no" >&5
@@ -2196,6 +2198,34 @@ echo "$as_me: error:
    { (exit 1); exit 1; }; }
 
     fi
+  else
+
+    WX_CFLAGS=""
+    WX_CPPFLAGS=""
+    WX_CXXFLAGS=""
+    WX_LIBS=""
+    WX_LIBS_STATIC=""
+
+        { { echo "$as_me:$LINENO: error:
+     	   wxWindows must be installed on your system
+     	   but wx-config script couldn't be found.
+
+     	   Please check that wx-config is in path, the directory
+     	   where wxWindows libraries are installed (returned by
+     	   'wx-config --libs' command) is in LD_LIBRARY_PATH or
+     	   equivalent variable and wxWindows version is 2.6.0 or above.
+        " >&5
+echo "$as_me: error:
+     	   wxWindows must be installed on your system
+     	   but wx-config script couldn't be found.
+
+     	   Please check that wx-config is in path, the directory
+     	   where wxWindows libraries are installed (returned by
+     	   'wx-config --libs' command) is in LD_LIBRARY_PATH or
+     	   equivalent variable and wxWindows version is 2.6.0 or above.
+        " >&2;}
+   { (exit 1); exit 1; }; }
+
   fi
 
 
@@ -4783,10 +4813,10 @@ fi
 
 
 
-    BAKEFILE_BAKEFILE_M4_VERSION="0.1.9.1"
+    BAKEFILE_BAKEFILE_M4_VERSION="0.1.9"
 
 
-BAKEFILE_AUTOCONF_INC_M4_VERSION="0.1.9.1"
+BAKEFILE_AUTOCONF_INC_M4_VERSION="0.1.9"
 
 
 
@@ -4945,6 +4975,11 @@ EOF
         COND_GCC_PCH_1=""
     fi
 
+    COND_ICC_PCH_1="#"
+    if test "x$ICC_PCH" = "x1" ; then
+        COND_ICC_PCH_1=""
+    fi
+
     COND_PLATFORM_MACOSX_1="#"
     if test "x$PLATFORM_MACOSX" = "x1" ; then
         COND_PLATFORM_MACOSX_1=""
@@ -4990,6 +5025,11 @@ EOF
         COND_USEDLL_1=""
     fi
 
+    COND_USE_PCH_1="#"
+    if test "x$USE_PCH" = "x1" ; then
+        COND_USE_PCH_1=""
+    fi
+
 
 
     if test "$BAKEFILE_AUTOCONF_INC_M4_VERSION" = "" ; then
@@ -5019,6 +5059,19 @@ fi
 cat >>confdefs.h <<_ACEOF
 #define FR_INSTALL_PREFIX "$FR_PREFIX"
 _ACEOF
+
+
+
+WX_INCLUDES=""
+for opt in $WX_CPPFLAGS
+do
+    case "$opt" in
+        -I*)
+            WX_INCLUDES="$WX_INCLUDES --include-dir `echo "$opt" | sed 's/^-I//'`"
+            ;;
+    esac
+done
+
 
 
 
@@ -5725,6 +5778,7 @@ s,@COND_DEPS_TRACKING_1@,$COND_DEPS_TRACKING_1,;t t
 s,@COND_FINAL_0@,$COND_FINAL_0,;t t
 s,@COND_FINAL_1@,$COND_FINAL_1,;t t
 s,@COND_GCC_PCH_1@,$COND_GCC_PCH_1,;t t
+s,@COND_ICC_PCH_1@,$COND_ICC_PCH_1,;t t
 s,@COND_PLATFORM_MACOSX_1@,$COND_PLATFORM_MACOSX_1,;t t
 s,@COND_PLATFORM_MAC_1@,$COND_PLATFORM_MAC_1,;t t
 s,@COND_PLATFORM_OS2_1@,$COND_PLATFORM_OS2_1,;t t
@@ -5734,6 +5788,8 @@ s,@COND_STATICRTL_0@,$COND_STATICRTL_0,;t t
 s,@COND_STATICRTL_1@,$COND_STATICRTL_1,;t t
 s,@COND_UNICODE_1@,$COND_UNICODE_1,;t t
 s,@COND_USEDLL_1@,$COND_USEDLL_1,;t t
+s,@COND_USE_PCH_1@,$COND_USE_PCH_1,;t t
+s,@WX_INCLUDES@,$WX_INCLUDES,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
