Update the files [...DEBIAN/{postinst, control}], delete the file [...DEBIAN/{preinst}]

diff --git a/templates/trees/deb/flamerobin/DEBIAN/postinst b/templates/trees/deb/flamerobin/DEBIAN/postinst
--- a/templates/trees/deb/flamerobin/DEBIAN/postinst
+++ b/templates/trees/deb/flamerobin/DEBIAN/postinst
@@ -36,7 +36,7 @@ fi
 
 if [[ ! -e "/usr/local/share/applications/" ]]
 then
-    mkdir -p  "/usr/local/share/applications" &> /dev/null 
+    mkdir -p  "/usr/local/share/applications" 2> /dev/null 
 
     #
     if [[ $? -ne 0 ]]
@@ -49,8 +49,13 @@ then
 fi
 
 #
-cp -r /opt/flamerobin/share/applications/flamerobin.desktop /usr/local/share/applications/ || \
-    { echo -e "Failed to copy the desktop file [ ...flamerobin.desktop -> /usr/local/share/applications ]"; exit 1; }
+if [[ -e "/opt/flamerobin/share/applications/flamerobin.desktop" ]]
+then
+    
+    #
+    cp -r /opt/flamerobin/share/applications/flamerobin.desktop /usr/local/share/applications/ || \
+        { echo -e "Failed to copy the desktop file [ ...flamerobin.desktop -> /usr/local/share/applications ]"; exit 1; }
+fi
 
 #
 update-desktop-database /usr/local/share/applications/ &> /dev/null 
@@ -64,15 +69,22 @@ if [[ -e "/usr/local/bin/" ]] && [[ -d "/usr/local/bin/" ]] && [[ ` echo "$PATH"
 then 
     
     #
-    ln -sf /opt/flamerobin/bin/flamerobin-launcher /usr/local/bin/flamerobin || \
-        { echo -e "Failed to create symlink in [ /usr/local/bin/ ]"; exit 1; }
+    if [[ -e "/opt/flamerobin/bin/flamerobin-launcher" ]]
+    then
+
+        ln -sf /opt/flamerobin/bin/flamerobin-launcher /usr/local/bin/flamerobin || \
+            { echo -e "Failed to create symlink in [ /usr/local/bin/ ]"; exit 1; }
+    fi
 
 elif [[ -e "/usr/bin/" ]] && [[ -d "/usr/bin/" ]] && [[ ` echo "$PATH" | grep "\/usr\/bin" ` ]]
 then
 
     #
-    ln -sf /opt/flamerobin/bin/flamerobin-launcher /usr/bin/flamerobin || \
-        { echo -e "Failed to create symlink in [ /usr/bin/ ]"; exit 1; }
+    if [[ -e "/opt/flamerobin/bin/flamerobin-launcher" ]]
+    then 
+        ln -sf /opt/flamerobin/bin/flamerobin-launcher /usr/bin/flamerobin || \
+            { echo -e "Failed to create symlink in [ /usr/bin/ ]"; exit 1; }
+    fi
 fi
 
 
@@ -83,3 +95,4 @@ echo ""
 echo "~"
 
 tput setaf 6; tput bold; echo "By Baldé ~" `tput sgr0` 2> /dev/null
+
