Update the file [...DEBIAN/{postinst}, .../opt/flamerobin/bin/flamerobin-launcher]

diff --git a/templates/trees/deb/flamerobin/DEBIAN/postinst b/templates/trees/deb/flamerobin/DEBIAN/postinst
--- a/templates/trees/deb/flamerobin/DEBIAN/postinst
+++ b/templates/trees/deb/flamerobin/DEBIAN/postinst
@@ -8,53 +8,36 @@ set -o pipefail
 
 
 
-### Check to see who executes the `flamerobin` program, then get the personnal directory
-#   of this user -> start tag[k0]
-
-# Declaration variables
-flagBehalfSudo=""
-getPersonalUserDir="$HOME"
-getTheRealUser="$USER"
-
-#
-if [[ -n "$SUDO_USER" ]]
-then
-    #
-    flagBehalfSudo="$SUDO_USER"
-    getTheRealUser="$SUDO_USER"
-
-    # Get the personnel directory of the user
-    getPersonalUserDir=$( getent passwd "$flagBehalfSudo" | cut -d ":" -f6 )
-fi
-
-### Check to see who executes the `flamerobin` program, then get the personnel directory
-#   of this user -> end tag[k0]
-
-
-
 ### Copy the `*.desktop` file of the flamerobin app to an appropriate directory -> start tag[df0]
 
-if [[ ! -e "/usr/local/share/applications/" ]]
+if [[ ! -d "/usr/local/share/applications/" ]]
 then
-    mkdir -p  "/usr/local/share/applications" 2> /dev/null 
 
     #
-    if [[ $? -ne 0 ]]
+    if ! mkdir -p  "/usr/local/share/applications" &> /dev/null 
     then
         echo "~"
-        echo -e "\033[1;031mMissing directory\033[0m -> [/usr/local/share/applications]"
+        echo -e "\033[1;31mMissing directory\033[0m -> [ /usr/local/share/applications ]"
 
         exit 1
     fi 
 fi
 
 #
-if [[ -e "/opt/flamerobin/share/applications/flamerobin.desktop" ]]
+if [[ -f "/opt/flamerobin/share/applications/flamerobin.desktop" ]]
 then
     
     #
-    cp -r /opt/flamerobin/share/applications/flamerobin.desktop /usr/local/share/applications/ || \
+    cp /opt/flamerobin/share/applications/flamerobin.desktop /usr/local/share/applications/ || \
         { echo -e "Failed to copy the desktop file [ ...flamerobin.desktop -> /usr/local/share/applications ]"; exit 1; }
+
+else
+    
+    #
+    echo "~"
+    echo -e "\033[1;31mMissing file\033[0m -> [ /opt/flamerobin/share/applications/flamerobin.desktop ]"
+
+    exit 1
 fi
 
 #
@@ -64,29 +47,44 @@ update-desktop-database /usr/local/share/applications/ &> /dev/null
 
 
 
-# Symbolic link for the executable (flamerobin) 
+### Symbolic link for the executable (flamerobin) -> start tag[sle0] 
+
+#
+if [[ ! -f "/opt/flamerobin/bin/flamerobin-launcher" ]]
+then
+
+    #
+    echo "~"
+    echo -e "\033[1;31mMissing file\033[0m -> [ /opt/flamerobin/bin/flamerobin-launcher ]"
+
+    exit 1
+fi
+
+
+#
 if [[ -e "/usr/local/bin/" ]] && [[ -d "/usr/local/bin/" ]] && [[ ` echo "$PATH" | grep "\/usr\/local\/bin" ` ]]
 then 
     
     #
-    if [[ -e "/opt/flamerobin/bin/flamerobin-launcher" ]]
-    then
-
-        ln -sf /opt/flamerobin/bin/flamerobin-launcher /usr/local/bin/flamerobin || \
-            { echo -e "Failed to create symlink in [ /usr/local/bin/ ]"; exit 1; }
-    fi
+    ln -sf /opt/flamerobin/bin/flamerobin-launcher /usr/local/bin/flamerobin || \
+        { echo -e "Failed to create symlink [ ...flamerobin-launcher -> /usr/local/bin/flamerobin ]"; exit 1; } 
 
 elif [[ -e "/usr/bin/" ]] && [[ -d "/usr/bin/" ]] && [[ ` echo "$PATH" | grep "\/usr\/bin" ` ]]
 then
 
     #
-    if [[ -e "/opt/flamerobin/bin/flamerobin-launcher" ]]
-    then 
-        ln -sf /opt/flamerobin/bin/flamerobin-launcher /usr/bin/flamerobin || \
-            { echo -e "Failed to create symlink in [ /usr/bin/ ]"; exit 1; }
-    fi
+    ln -sf /opt/flamerobin/bin/flamerobin-launcher /usr/bin/flamerobin || \
+        { echo -e "Failed to create symlink [ ...flamerobin-launcher ->  /usr/bin/flamerobin ]"; exit 1; }
+
+else
+    
+    echo "~"
+    echo -e "\033[1;31mMissing directories\033[0m -> [ /usr/local/bin/ , /usr/bin/ ]"
+
+    exit 1
 fi
 
+### Symbolic link for the executable (flamerobin) -> end tag[sle0] 
 
 
 # Just to print the name of the author
